language: python

python:
  - 3.8

services:
  postgresql
addons:
  postgresql: '9.5'

before_install:
  - pip install poetry

  install:
  - poetry install
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testedb;" -U postgres

  script:
  - poetry run flake8 .
  - poetry run pytest --cov=pypro

after_success:
  - poetry run codecov
