language: python

python:
  - 3.8
before_install:
  - pip install poetry
install:
  - poetry install
  - cp contrib/env-sample .env
script:
  - poetry run flake8 .
  - poetry run pytest --cov=pypro

after_success:
  - poetry run codecov
